//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlaceReservaHotelExtra
    {
        public int ReservaHotelId { get; set; }
        public int ExtraId { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Extra Extra { get; set; }
        public virtual ReservaHotel ReservaHotel { get; set; }
    }
}
