//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlaceReservaHotelPasajero
    {
        public int ReservaHotelId { get; set; }
        public int PasajeroId { get; set; }
        public int PaqueteId { get; set; }
        public byte BaseId { get; set; }
        public int ID { get; set; }
    
        public virtual Paquete Paquete { get; set; }
        public virtual Pasajero Pasajero { get; set; }
        public virtual ReservaHotel ReservaHotel { get; set; }
        public virtual TipoBase TipoBase { get; set; }
    }
}
