//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlaceBusPasajero
    {
        public int BusId { get; set; }
        public int PasajeroId { get; set; }
        public Nullable<int> NroButaca { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Pasajero Pasajero { get; set; }
    }
}
