//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlaceReservaHotelDescuento
    {
        public int ID { get; set; }
        public int ReservaHotelId { get; set; }
        public double Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> PagoId { get; set; }
    
        public virtual ReservaHotel ReservaHotel { get; set; }
        public virtual EnlaceReservaHotelPago EnlaceReservaHotelPago { get; set; }
    }
}
