//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlaceReservaHotelPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnlaceReservaHotelPago()
        {
            this.EnlaceReservaHotelDescuento = new HashSet<EnlaceReservaHotelDescuento>();
        }
    
        public int ID { get; set; }
        public int ReservaHotelId { get; set; }
        public int TipoFormaDePagoId { get; set; }
        public double Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> NroComprobante { get; set; }
        public string NombreTitular { get; set; }
        public Nullable<int> DniTitular { get; set; }
    
        public virtual ReservaHotel ReservaHotel { get; set; }
        public virtual TipoFormaDePago TipoFormaDePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelDescuento> EnlaceReservaHotelDescuento { get; set; }
    }
}
