//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlaceReservaHotelHabitacion
    {
        public int ReservaHotelId { get; set; }
        public int HabitacionId { get; set; }
        public int TipoHabitacionId { get; set; }
        public int ID { get; set; }
    
        public virtual TipoHabitacion TipoHabitacion { get; set; }
        public virtual Habitacion Habitacion { get; set; }
        public virtual ReservaHotel ReservaHotel { get; set; }
    }
}
