//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitacion()
        {
            this.EnlaceReservaHotelHabitacion = new HashSet<EnlaceReservaHotelHabitacion>();
            this.TipoHabitacion = new HashSet<TipoHabitacion>();
        }
    
        public int ID { get; set; }
        public byte HotelId { get; set; }
        public byte Piso { get; set; }
        public int Numero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelHabitacion> EnlaceReservaHotelHabitacion { get; set; }
        public virtual TipoHotel TipoHotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoHabitacion> TipoHabitacion { get; set; }
    }
}
