//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuAspNetRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuAspNetRoles()
        {
            this.MenuAspNetRolesAccion = new HashSet<MenuAspNetRolesAccion>();
        }
    
        public int ID { get; set; }
        public int MenuId { get; set; }
        public string AspNetRolesId { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuAspNetRolesAccion> MenuAspNetRolesAccion { get; set; }
    }
}
