//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paquete()
        {
            this.EnlaceReservaHotelPasajero = new HashSet<EnlaceReservaHotelPasajero>();
            this.Ventanilla = new HashSet<Ventanilla>();
        }
    
        public int ID { get; set; }
        public string Titulo { get; set; }
        public byte DescripcionId { get; set; }
        public byte TemporadaId { get; set; }
        public byte NochesId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public double PrecioSingle { get; set; }
        public double PrecioDoble { get; set; }
        public byte CuotasId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool BusIda { get; set; }
        public bool BusVuelta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelPasajero> EnlaceReservaHotelPasajero { get; set; }
        public virtual TipoCuota TipoCuota { get; set; }
        public virtual TipoDescripcionPaquete TipoDescripcionPaquete { get; set; }
        public virtual TipoNoche TipoNoche { get; set; }
        public virtual TipoTemporada TipoTemporada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventanilla> Ventanilla { get; set; }
    }
}
