//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasajero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pasajero()
        {
            this.EnlaceBusPasajero = new HashSet<EnlaceBusPasajero>();
            this.EnlaceReservaHotelPasajero = new HashSet<EnlaceReservaHotelPasajero>();
            this.ReservaHotel = new HashSet<ReservaHotel>();
        }
    
        public int ID { get; set; }
        public long DNI { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public byte Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<long> Telefono { get; set; }
        public string Email { get; set; }
        public bool Diabetes { get; set; }
        public bool Celiaquia { get; set; }
        public bool Motricidad { get; set; }
        public bool ListaNegra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceBusPasajero> EnlaceBusPasajero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelPasajero> EnlaceReservaHotelPasajero { get; set; }
        public virtual TipoSexo TipoSexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaHotel> ReservaHotel { get; set; }
    }
}
