//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasajero
    {
        public int ID { get; set; }
        public long DNI { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public byte Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Email { get; set; }
        public bool Diabetes { get; set; }
        public bool Celiaquia { get; set; }
        public bool Motricidad { get; set; }
        public bool ListaNegra { get; set; }
        public Nullable<long> Telefono { get; set; }
    
        public virtual TipoSexo TipoSexo { get; set; }
    }
}
