//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaHotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservaHotel()
        {
            this.EnlaceReservaHotelHabitacion = new HashSet<EnlaceReservaHotelHabitacion>();
            this.EnlaceReservaHotelPasajero = new HashSet<EnlaceReservaHotelPasajero>();
        }
    
        public int ID { get; set; }
        public int TitularId { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public byte HotelId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public bool Confirmada { get; set; }
        public Nullable<System.DateTime> FechaComfirmada { get; set; }
        public string UsuarioConfirma { get; set; }
        public Nullable<System.DateTime> FechaCancelada { get; set; }
        public string UsuarioCancela { get; set; }
        public bool Activa { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual AspNetUsers AspNetUsers3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelHabitacion> EnlaceReservaHotelHabitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelPasajero> EnlaceReservaHotelPasajero { get; set; }
        public virtual Pasajero Pasajero { get; set; }
        public virtual TipoHotel TipoHotel { get; set; }
    }
}
