//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaroHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaHotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservaHotel()
        {
            this.EnlaceReservaHotelPasajero = new HashSet<EnlaceReservaHotelPasajero>();
            this.Bus = new HashSet<Bus>();
            this.EnlaceReservaHotelDescuento = new HashSet<EnlaceReservaHotelDescuento>();
            this.EnlaceReservaHotelPago = new HashSet<EnlaceReservaHotelPago>();
            this.EnlaceReservaHotelExtra = new HashSet<EnlaceReservaHotelExtra>();
            this.EnlaceReservaHotelHabitacion = new HashSet<EnlaceReservaHotelHabitacion>();
        }
    
        public int ID { get; set; }
        public int TitularId { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public byte HotelId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public bool Confirmada { get; set; }
        public Nullable<System.DateTime> FechaComfirmada { get; set; }
        public string UsuarioConfirma { get; set; }
        public Nullable<System.DateTime> FechaCancelada { get; set; }
        public string UsuarioCancela { get; set; }
        public bool Activa { get; set; }
        public int FormaDePagoId { get; set; }
        public string Observaciones { get; set; }
        public int VentanillaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelPasajero> EnlaceReservaHotelPasajero { get; set; }
        public virtual Pasajero Pasajero { get; set; }
        public virtual TipoHotel TipoHotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
        public virtual TipoFormaDePago TipoFormaDePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelDescuento> EnlaceReservaHotelDescuento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelPago> EnlaceReservaHotelPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelExtra> EnlaceReservaHotelExtra { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual AspNetUsers AspNetUsers3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnlaceReservaHotelHabitacion> EnlaceReservaHotelHabitacion { get; set; }
        public virtual Ventanilla Ventanilla { get; set; }
    }
}
